Data Cleaning

In [1]:
import pandas as pd

In [2]:
file=pd.read_csv("MOBILE.csv")

In [3]:
file

,Unnamed: 0,Name,price,offer
0,0,ILOZ Luxury New Elegance Rose Gold white Wome...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹299.00...","<span class=""jm-badge""> 62% OFF </span>"
1,1,Acnos Analog White Dial Rose Gold Strap Watch...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹209.00...","<span class=""jm-badge""> 89% OFF </span>"
2,2,Acnos Brand Digital Silver Vintage Square Dia...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹229.00...","<span class=""jm-badge""> 84% OFF </span>"
3,3,WATCHVERSE New Tranding Designer Black Rose G...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹199.00...","<span class=""jm-badge""> 75% OFF </span>"
4,4,Acnos Brand Digital Black Vintage Square Dial...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹229.00...","<span class=""jm-badge""> 84% OFF </span>"
5,5,Stojira Artist Analog Blue Dial Blue Strap Wa...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹299.00...","<span class=""jm-badge""> 62% OFF </span>"
6,6,Lorenz Slim Case Analog Watch with Black Magn...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹380.00...","<span class=""jm-badge""> 84% OFF </span>"
7,7,Lorenz Black Date Dial Analog Watch with Blac...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹454.00...","<span class=""jm-badge""> 81% OFF </span>"
8,8,Acnos Brand Digital Rosegold Vintage Square D...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹239.00...","<span class=""jm-badge""> 84% OFF </span>"
9,9,FOGG 4075-SL Elegant Design Analog Watch - Fo...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹259.00...","<span class=""jm-badge""> 85% OFF </span>"
10,10,Acnos Analog White Dial Rose Gold Strap Watch...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹209.00...","<span class=""jm-badge""> 89% OFF </span>"
11,11,ILOZ Luxury New Elegance Rose Gold maroon Wom...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹299.00...","<span class=""jm-badge""> 62% OFF </span>"

In [4]:
file.drop("Unnamed: 0",axis=1)

,Name,price,offer
0,ILOZ Luxury New Elegance Rose Gold white Wome...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹299.00...","<span class=""jm-badge""> 62% OFF </span>"
1,Acnos Analog White Dial Rose Gold Strap Watch...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹209.00...","<span class=""jm-badge""> 89% OFF </span>"
2,Acnos Brand Digital Silver Vintage Square Dia...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹229.00...","<span class=""jm-badge""> 84% OFF </span>"
3,WATCHVERSE New Tranding Designer Black Rose G...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹199.00...","<span class=""jm-badge""> 75% OFF </span>"
4,Acnos Brand Digital Black Vintage Square Dial...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹229.00...","<span class=""jm-badge""> 84% OFF </span>"
5,Stojira Artist Analog Blue Dial Blue Strap Wa...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹299.00...","<span class=""jm-badge""> 62% OFF </span>"
6,Lorenz Slim Case Analog Watch with Black Magn...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹380.00...","<span class=""jm-badge""> 84% OFF </span>"
7,Lorenz Black Date Dial Analog Watch with Blac...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹454.00...","<span class=""jm-badge""> 81% OFF </span>"
8,Acnos Brand Digital Rosegold Vintage Square D...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹239.00...","<span class=""jm-badge""> 84% OFF </span>"
9,FOGG 4075-SL Elegant Design Analog Watch - Fo...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹259.00...","<span class=""jm-badge""> 85% OFF </span>"
10,Acnos Analog White Dial Rose Gold Strap Watch...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹209.00...","<span class=""jm-badge""> 89% OFF </span>"
11,ILOZ Luxury New Elegance Rose Gold maroon Wom...,"<span class=""jm-heading-xxs jm-mb-xxs"">₹299.00...","<span class=""jm-badge""> 62% OFF </span>"

In [9]:
file["offer"]=file["offer"].str.strip('<span class="jm-badge"> % OFF </span>').astype(str)

In [7]:
file["price"]=file["price"].str.strip('<span class="jm-heading-xxs jm-mb-xxs" </span>').astype(str)

In [11]:
file.drop("Unnamed: 0",axis=1)

                                                 Name    price offer
0    ILOZ Luxury New Elegance Rose Gold white Wome...  ₹299.00    62
1    Acnos Analog White Dial Rose Gold Strap Watch...  ₹209.00    89
2    Acnos Brand Digital Silver Vintage Square Dia...  ₹229.00    84
3    WATCHVERSE New Tranding Designer Black Rose G...  ₹199.00    75
4    Acnos Brand Digital Black Vintage Square Dial...  ₹229.00    84
5    Stojira Artist Analog Blue Dial Blue Strap Wa...  ₹299.00    62
6    Lorenz Slim Case Analog Watch with Black Magn...  ₹380.00    84
7    Lorenz Black Date Dial Analog Watch with Blac...  ₹454.00    81
8    Acnos Brand Digital Rosegold Vintage Square D...  ₹239.00    84
9    FOGG 4075-SL Elegant Design Analog Watch - Fo...  ₹259.00    85
10   Acnos Analog White Dial Rose Gold Strap Watch...  ₹209.00    89
11   ILOZ Luxury New Elegance Rose Gold maroon Wom...  ₹299.00    62

In [14]:
file

,Unnamed: 0,Name,price,offer
0,0,ILOZ Luxury New Elegance Rose Gold white Wome...,₹299.00,62
1,1,Acnos Analog White Dial Rose Gold Strap Watch...,₹209.00,89
2,2,Acnos Brand Digital Silver Vintage Square Dia...,₹229.00,84
3,3,WATCHVERSE New Tranding Designer Black Rose G...,₹199.00,75
4,4,Acnos Brand Digital Black Vintage Square Dial...,₹229.00,84
5,5,Stojira Artist Analog Blue Dial Blue Strap Wa...,₹299.00,62
6,6,Lorenz Slim Case Analog Watch with Black Magn...,₹380.00,84
7,7,Lorenz Black Date Dial Analog Watch with Blac...,₹454.00,81
8,8,Acnos Brand Digital Rosegold Vintage Square D...,₹239.00,84
9,9,FOGG 4075-SL Elegant Design Analog Watch - Fo...,₹259.00,85
10,10,Acnos Analog White Dial Rose Gold Strap Watch...,₹209.00,89
11,11,ILOZ Luxury New Elegance Rose Gold maroon Wom...,₹299.00,62

catogorical data

In [17]:
salary=pd.DataFrame({"salary":[10000,200000,300000,400000,500000,600000],"range":['low','low','mid','mid','high','high']})

In [18]:
salary

   salary range
0   10000   low
1  200000   low
2  300000   mid
3  400000   mid
4  500000  high
5  600000  high

In [20]:
code=salary.range.map({'low':3,'high':1,'mid':2})

In [21]:
code

0    3
1    3
2    2
3    2
4    1
5    1
Name: range, dtype: int64